// Tab bar controller and tab bar tabs.
import 'package:built_value/built_value.dart';

List<String> tabTextList = [
  "Business",
  "Entertainment",
  "General",
  "Health",
  "Science",
  "Sports",
  "Technology",
];

/* The dictionary of country name - country code pairs supported by the API
 * associated with this application. **/
Map<String, String> countryCodeDictionary = {
  "Argentina": "ar",
  "Australia": "au",
  "Austria": "at",
  "Belgium": "be",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Canada": "ca",
  "China": "cn",
  "Colombia": "co",
  "Cuba": "cu",
  "Czech Republic": "cz",
  "Egypt": "eg",
  "France": "fr",
  "Germany": "de",
  "Greece": "gr",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "India": "in",
  "Indonesia": "id",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Japan": "jp",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Malaysia": "my",
  "Mexico": "mx",
  "Morocco": "ma",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nigeria": "ng",
  "Norway": "no",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Romania": "ro",
  "Russia": "ru",
  "Saudi Arab": "sa",
  "Serbia": "rs",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Taiwan": "tw",
  "Thailand": "th",
  "Turkey": "tr",
  "UAE": "ae",
  "Ukraine": "ua",
  "United Kingdom": "gb",
  "United States": "us",
  "Venezuela": "ve",
};

CurrentPlatform currentPlatform = CurrentPlatform.iOS;
enum CurrentPlatform {
  iOS,
  android,
  web,
}
